project:
  type: website

website:
  title: "Khaled Aliyan"

  navbar:
    background: "#0b0f19"
    foreground: "#ffffff"

    left:
      - href: index.md
        text: Home

      - href: about.md
        text: About

      - href: projects.md
        text: Projects

      - href: blog/index.md
        text: Blog

    right:
      - icon: github
        href: https://github.com/KhaledAliyanCS

      - text: Resume
        href: resume.pdf

format:
  html:
    theme:
      light: flatly
      dark: cyborg
    css: styles.css
    toc: false
    smooth-scroll: true